PACKAGE_NAME="mt7902-wifi"
PACKAGE_VERSION="1.0"
MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules"
CLEAN="make clean"

BUILT_MODULE_NAME[0]="mt76"
DEST_MODULE_LOCATION[0]="/updates/mt76"

BUILT_MODULE_NAME[1]="mt76-connac-lib"
DEST_MODULE_LOCATION[1]="/updates/mt76"

BUILT_MODULE_NAME[2]="mt792x-lib"
DEST_MODULE_LOCATION[2]="/updates/mt76"

BUILT_MODULE_NAME[3]="mt7921-common"
BUILT_MODULE_LOCATION[3]="mt7921/"
DEST_MODULE_LOCATION[3]="/updates/mt76"

BUILT_MODULE_NAME[4]="mt7921e"
BUILT_MODULE_LOCATION[4]="mt7921/"
DEST_MODULE_LOCATION[4]="/updates/mt76"

BUILT_MODULE_NAME[5]="btmtk"
BUILT_MODULE_LOCATION[5]="bluetooth/"
DEST_MODULE_LOCATION[5]="/updates/bluetooth"

BUILT_MODULE_NAME[6]="btusb"
BUILT_MODULE_LOCATION[6]="bluetooth/"
DEST_MODULE_LOCATION[6]="/updates/bluetooth"

AUTOINSTALL="yes"
